"""Monodromy, ribbon graphs, and canonical homology bases."""

from fractions import Fraction

from ._records import (
    _BranchGenerator, _BranchLoopStep, _CanonicalPolygon, _GraphCycleWord,
    _LiftedGraphEdge, _LiftedMonodromyGraph, _LiftedPathTerm, _MonodromyData,
    _NumericalCanonicalPolygon, _NumericalGraphCycles, _OrderedMonodromyData,
    _RibbonCutSystem, _SymplecticReduction,
)
from .continuation import (
    _align_closed_continuation_base_fibre,
    _concatenate_plane_curve_continuations,
    _continue_plane_curve_sheets_adaptive, _lifted_path_chain_boundary,
    _lifted_path_endpoints, _prepare_lifted_path_chain, _radial_branch_geometry,
    _radial_branch_loop_path, _real_branch_loop_path,
    _reverse_plane_curve_continuation, _same_numerical_place,
)
from .polynomial import _ordered_plane_curve_sheets

# Monodromy invariants
# --------------------

def _compose_permutations(left, right):
    """Return ``left`` after ``right`` for permutation image tuples."""
    if len(left) != len(right):
        raise ValueError("permutations must have equal sizes")
    return tuple(left[right[index]] for index in range(len(left)))


def _inverse_permutation(permutation):
    """Return the inverse of a permutation image tuple."""
    if sorted(permutation) != list(range(len(permutation))):
        raise ValueError("invalid permutation")
    return tuple(permutation.index(index)
                 for index in range(len(permutation)))


def _permutation_cycles(permutation, include_fixed=False):
    """Return the disjoint cycles of a permutation."""
    if sorted(permutation) != list(range(len(permutation))):
        raise ValueError("invalid permutation")
    visited = set()
    cycles = []
    for start in range(len(permutation)):
        if start in visited:
            continue
        cycle = []
        current = start
        while current not in visited:
            visited.add(current)
            cycle.append(current)
            current = permutation[current]
        if include_fixed or len(cycle) > 1:
            cycles.append(tuple(cycle))
    return tuple(cycles)


def _monodromy_orbit(permutations, start=0):
    """Return the sheet orbit generated by a sequence of permutations."""
    orbit = {start}
    pending = [start]
    while pending:
        sheet = pending.pop()
        for permutation in permutations:
            image = permutation[sheet]
            if image not in orbit:
                orbit.add(image)
                pending.append(image)
    return frozenset(orbit)


def _riemann_hurwitz_genus(degree, permutations):
    """Return genus and total ramification for a connected sphere cover."""
    ramification = sum(
        sum(len(cycle) - 1
            for cycle in _permutation_cycles(permutation))
        for permutation in permutations)
    numerator = 2 - 2 * degree + ramification
    if numerator < 0 or numerator % 2:
        raise ValueError("monodromy data do not define a valid genus")
    return numerator // 2, ramification


def _integer_matrix_rank(matrix):
    """Return the exact rational rank of an integer matrix."""
    rows = [list(map(Fraction, row)) for row in matrix]
    if not rows:
        return 0
    row_count = len(rows)
    column_count = len(rows[0])
    rank = 0
    for column in range(column_count):
        pivot = next((row for row in range(rank, row_count)
                      if rows[row][column]), None)
        if pivot is None:
            continue
        rows[rank], rows[pivot] = rows[pivot], rows[rank]
        pivot_value = rows[rank][column]
        rows[rank] = [value / pivot_value for value in rows[rank]]
        for row in range(row_count):
            if row == rank or not rows[row][column]:
                continue
            multiplier = rows[row][column]
            rows[row] = [
                value - multiplier * pivot_entry
                for value, pivot_entry in zip(rows[row], rows[rank])]
        rank += 1
        if rank == row_count:
            break
    return rank


def _integer_determinant(matrix):
    """Return the exact determinant of a square integer matrix."""
    size = len(matrix)
    if any(len(row) != size for row in matrix):
        raise ValueError("determinant requires a square matrix")
    if not size:
        return 1
    work = [list(row) for row in matrix]
    sign = 1
    previous = 1
    for column in range(size - 1):
        pivot = next((row for row in range(column, size)
                      if work[row][column]), None)
        if pivot is None:
            return 0
        if pivot != column:
            work[column], work[pivot] = work[pivot], work[column]
            sign = -sign
        pivot_value = work[column][column]
        for row in range(column + 1, size):
            for entry in range(column + 1, size):
                numerator = (
                    work[row][entry] * pivot_value
                    - work[row][column] * work[column][entry])
                work[row][entry] = numerator // previous
        previous = pivot_value
    return sign * work[-1][-1]


def _symplectic_reduce_intersection(matrix):
    """Reduce a primitive integral skew form to canonical form.

    Rows of the returned transformation express the canonical symplectic and
    radical generators in the input basis.
    """
    matrix = tuple(tuple(int(value) for value in row) for row in matrix)
    size = len(matrix)
    if any(len(row) != size for row in matrix):
        raise ValueError("intersection matrix must be square")
    if any(matrix[row][column] != -matrix[column][row]
           for row in range(size) for column in range(size)):
        raise ValueError("intersection matrix must be skew-symmetric")

    def pairing(left, right):
        return sum(
            left[row] * matrix[row][column] * right[column]
            for row in range(size) for column in range(size))

    remaining = [tuple(1 if row == column else 0
                       for column in range(size))
                 for row in range(size)]
    a_vectors = []
    b_vectors = []
    while True:
        pair = next((
            (left, right)
            for left in range(len(remaining))
            for right in range(left + 1, len(remaining))
            if abs(pairing(remaining[left], remaining[right])) == 1
        ), None)
        if pair is None:
            break
        left_index, right_index = pair
        left = remaining[left_index]
        right = remaining[right_index]
        if pairing(left, right) == -1:
            right = tuple(-value for value in right)
        remaining = [
            vector for index, vector in enumerate(remaining)
            if index not in pair]

        orthogonal = []
        for vector in remaining:
            left_coefficient = pairing(vector, right)
            right_coefficient = pairing(vector, left)
            orthogonal.append(tuple(
                value - left_coefficient * left_value
                + right_coefficient * right_value
                for value, left_value, right_value
                in zip(vector, left, right)))
        a_vectors.append(left)
        b_vectors.append(right)
        remaining = orthogonal

    if any(pairing(left, right)
           for left in remaining for right in remaining):
        raise ValueError(
            "intersection form is not primitively symplectic")
    transformation = tuple(a_vectors + b_vectors + remaining)
    if abs(_integer_determinant(transformation)) != 1:
        raise ValueError("symplectic reduction is not unimodular")
    form = tuple(
        tuple(pairing(left, right) for right in transformation)
        for left in transformation)
    genus = len(a_vectors)
    radical_rank = len(remaining)
    return _SymplecticReduction(
        transformation=transformation,
        form=form,
        genus=genus,
        radical_rank=radical_rank,
    )


def _tree_path(adjacency, start, end):
    """Return oriented edge steps along the unique path in a tree."""
    pending = [(start, ())]
    visited = {start}
    while pending:
        vertex, path = pending.pop()
        if vertex == end:
            return path
        for neighbor, edge, orientation in adjacency[vertex]:
            if neighbor not in visited:
                visited.add(neighbor)
                pending.append((
                    neighbor, path + ((edge, orientation),)))
    raise ValueError("lifted graph is disconnected")


def _ribbon_boundary_orbits(edges, rotation, included_edges=None):
    """Return oriented boundary orbits of a thickened ribbon subgraph."""
    if included_edges is None:
        included_edges = set(range(len(edges)))
    else:
        included_edges = set(included_edges)
    successor = {}
    for half_edges in rotation.values():
        half_edges = tuple(
            half_edge for half_edge in half_edges
            if half_edge[0] in included_edges)
        if not half_edges:
            continue
        for index, half_edge in enumerate(half_edges):
            successor[half_edge] = half_edges[(index + 1) % len(half_edges)]

    def boundary_step(half_edge):
        edge, endpoint = half_edge
        return successor[(edge, 1 - endpoint)]

    unvisited = set(successor)
    orbits = []
    while unvisited:
        start = next(iter(unvisited))
        current = start
        orbit = []
        while current in unvisited:
            unvisited.remove(current)
            orbit.append(current)
            current = boundary_step(current)
        if current != start:
            raise ValueError("ribbon boundary orbit does not close")
        orbits.append(tuple(orbit))
    return tuple(orbits)


def _ribbon_boundary_count(edges, rotation):
    """Count boundary components of the oriented thickened graph."""
    return len(_ribbon_boundary_orbits(edges, rotation))


def _ribbon_tree_cotree_cut_system(
        graph, tree_edges=None, cotree_edge_order=None, root=None):
    """Construct a certified one-face cut system of a ribbon graph.

    This is the tree--cotree construction of Eppstein, *Dynamic generators
    of topologically embedded graphs*, SODA 2003, arXiv:cs/0207082, and
    Erickson--Whittlesey, *Greedy optimal homotopy and homology generators*,
    SODA 2005.  The returned loops retain oriented graph-edge paths; unlike a
    homology matrix alone, that data can later support a canonical polygon
    and iterated path integrals.

    ``tree_edges``, ``cotree_edge_order`` and ``root`` are private robustness
    hooks: they allow independently admissible choices to be compared without
    changing the deterministic production choice.  Every supplied choice is
    certified below before it is used.
    """
    edges = graph.edges
    if tree_edges is None:
        tree_edges = tuple(graph.tree_edges)
    else:
        tree_edges = tuple(tree_edges)
    if (len(tree_edges) != len(graph.vertices) - 1
            or len(set(tree_edges)) != len(tree_edges)
            or any(not isinstance(edge, int) or edge < 0
                   or edge >= len(edges) for edge in tree_edges)):
        raise ValueError("tree edges do not form a spanning tree")

    tree_parent = {vertex: vertex for vertex in graph.vertices}

    def tree_find(vertex):
        while tree_parent[vertex] != vertex:
            tree_parent[vertex] = tree_parent[tree_parent[vertex]]
            vertex = tree_parent[vertex]
        return vertex

    for edge_index in tree_edges:
        edge = edges[edge_index]
        left = tree_find(edge.tail)
        right = tree_find(edge.head)
        if left == right:
            raise ValueError("tree edges do not form a spanning tree")
        tree_parent[left] = right
    if len({tree_find(vertex) for vertex in graph.vertices}) != 1:
        raise ValueError("tree edges do not form a spanning tree")

    tree_set = set(tree_edges)
    faces = _ribbon_boundary_orbits(edges, graph.rotation)
    half_edge_face = {
        half_edge: face_index
        for face_index, face in enumerate(faces)
        for half_edge in face
    }

    parent = list(range(len(faces)))

    def find(index):
        while parent[index] != index:
            parent[index] = parent[parent[index]]
            index = parent[index]
        return index

    complement = tuple(
        edge_index for edge_index in range(len(edges))
        if edge_index not in tree_set)
    if cotree_edge_order is None:
        cotree_edge_order = complement
    else:
        cotree_edge_order = tuple(cotree_edge_order)
        if (len(cotree_edge_order) != len(complement)
                or set(cotree_edge_order) != set(complement)):
            raise ValueError(
                "cotree edge order must permute the tree complement")

    cotree_edges = []
    for edge_index in cotree_edge_order:
        left = find(half_edge_face[(edge_index, 0)])
        right = find(half_edge_face[(edge_index, 1)])
        if left != right:
            parent[left] = right
            cotree_edges.append(edge_index)
    if len(cotree_edges) != len(faces) - 1:
        raise ValueError("dual complement of ribbon tree is disconnected")

    cotree_set = set(cotree_edges)
    generator_edges = tuple(
        edge_index for edge_index in range(len(edges))
        if edge_index not in tree_set and edge_index not in cotree_set)
    if len(generator_edges) != 2 * graph.genus:
        raise ValueError("tree-cotree complement does not have 2*g edges")

    cut_edges = tree_set | set(generator_edges)
    cut_boundaries = _ribbon_boundary_orbits(
        edges, graph.rotation, cut_edges)
    if len(cut_boundaries) != 1:
        raise ValueError("tree-cotree cut system does not have one face")
    boundary_word = tuple(
        (edge_index, 1 if endpoint == 0 else -1)
        for edge_index, endpoint in cut_boundaries[0]
        if edge_index in generator_edges)
    if len(boundary_word) != 4 * graph.genus:
        raise ValueError("cut-system polygon has the wrong side count")
    for edge_index in generator_edges:
        occurrences = tuple(
            orientation for edge, orientation in boundary_word
            if edge == edge_index)
        if sorted(occurrences) != [-1, 1]:
            raise ValueError("cut-system side pairing is inconsistent")

    adjacency = {vertex: [] for vertex in graph.vertices}
    for edge_index in tree_edges:
        edge = edges[edge_index]
        adjacency[edge.tail].append((edge.head, edge_index, 1))
        adjacency[edge.head].append((edge.tail, edge_index, -1))
    if root is None:
        root = min(graph.vertices)
    elif root not in set(graph.vertices) or root[0] != "base":
        raise ValueError("cut-system root must be a base-sheet vertex")
    loops = []
    cycles = []
    for edge_index in generator_edges:
        edge = edges[edge_index]
        loop = (_tree_path(adjacency, root, edge.tail)
                + ((edge_index, 1),)
                + _tree_path(adjacency, edge.head, root))
        coefficients = [0] * len(edges)
        for loop_edge, orientation in loop:
            coefficients[loop_edge] += orientation
        if any(coefficient not in (-1, 0, 1)
               for coefficient in coefficients):
            raise ValueError("cut-system loop repeats an oriented edge")
        loops.append(loop)
        cycles.append(tuple(coefficients))
    intersection = tuple(
        tuple(_ribbon_cycle_intersection(
            edges, graph.rotation, left, right) for right in cycles)
        for left in cycles)
    if _integer_matrix_rank(intersection) != 2 * graph.genus:
        raise ValueError("cut-system loops have degenerate intersection")
    return _RibbonCutSystem(
        root=root,
        tree_edges=tree_edges,
        cotree_edges=tuple(cotree_edges),
        generator_edges=generator_edges,
        loops=tuple(loops),
        boundary_word=boundary_word,
        intersection=intersection,
    )


def _inverse_oriented_word(word):
    """Return the inverse of a word of ``(symbol, orientation)`` pairs."""
    return tuple((symbol, -orientation)
                 for symbol, orientation in reversed(word))


def _free_reduce_oriented_word(word):
    """Cancel adjacent inverse pairs in an oriented word."""
    reduced = []
    for symbol, orientation in word:
        token = (symbol, orientation)
        if reduced and reduced[-1] == (symbol, -orientation):
            reduced.pop()
        else:
            reduced.append(token)
    return tuple(reduced)


def _brahana_canonical_words(boundary_word):
    """Rewrite an orientable polygon word as canonical commutators.

    This implements Step 2 of the Brahana transformation as stated in
    Lazarus--Pocchiola--Vegter--Verroust, *Computing a Canonical Polygonal
    Schema of an Orientable Triangulated Surface*, SoCG 2001, Section 5.
    Every returned generator remains an explicit free-group word in the
    input sides; no abelianization or homology-only substitution is used.
    """
    remaining = tuple(boundary_word)
    if len(remaining) % 4:
        raise ValueError("orientable polygon must have 4*g sides")
    symbols = {symbol for symbol, unused in remaining}
    for symbol in symbols:
        occurrences = tuple(
            orientation for candidate, orientation in remaining
            if candidate == symbol)
        if sorted(occurrences) != [-1, 1]:
            raise ValueError(
                "orientable polygon sides must occur with opposite signs")

    pairs = []
    while remaining:
        a = remaining[0]
        a_inverse = (a[0], -a[1])
        try:
            a_inverse_index = remaining.index(a_inverse, 1)
        except ValueError:
            raise ValueError("polygon side has no inverse partner")

        crossing = None
        for b_index in range(1, a_inverse_index):
            b = remaining[b_index]
            b_inverse = (b[0], -b[1])
            try:
                b_inverse_index = remaining.index(
                    b_inverse, a_inverse_index + 1)
            except ValueError:
                continue
            crossing = b_index, b_inverse_index
            break
        if crossing is None:
            raise ValueError(
                "polygon word has no interlaced orientable handle")
        b_index, b_inverse_index = crossing
        b = remaining[b_index]
        x1 = remaining[1:b_index]
        x2 = remaining[b_index + 1:a_inverse_index]
        x3 = remaining[a_inverse_index + 1:b_inverse_index]
        x4 = remaining[b_inverse_index + 1:]

        # With M = a X1 b X2 a^-1 X3 b^-1 X4, Brahana's
        # x = a X1 b X2 a^-1 and y = X3 X2 a^-1 give the exact free-word
        # identity M = [x,y] X3 X2 X1 X4.
        x = _free_reduce_oriented_word(
            (a,) + x1 + (b,) + x2 + (a_inverse,))
        y = _free_reduce_oriented_word(x3 + x2 + (a_inverse,))
        pairs.append((x, y))
        remaining = x3 + x2 + x1 + x4

    relator = ()
    for a, b in pairs:
        relator = _free_reduce_oriented_word(
            relator + a + b
            + _inverse_oriented_word(a)
            + _inverse_oriented_word(b))
    if relator != tuple(boundary_word):
        raise ValueError(
            "canonical commutators do not reproduce the polygon relator")
    return tuple(pairs)


def _expand_cut_system_word(word, generator_loops):
    """Expand a free word in cut generators to oriented ribbon edges."""
    result = ()
    for generator, orientation in word:
        try:
            loop = generator_loops[generator]
        except IndexError:
            raise ValueError("canonical word has an invalid generator")
        if orientation == -1:
            loop = _inverse_oriented_word(loop)
        elif orientation != 1:
            raise ValueError("word orientations must be +1 or -1")
        result = _free_reduce_oriented_word(result + loop)
    return result


def _canonical_ribbon_polygon(graph, cut_system=None):
    """Return canonical based loops with their exact polygon relator.

    The word conversion is Brahana's algorithm in Section 5 of
    Lazarus--Pocchiola--Vegter--Verroust (SoCG 2001).  Keeping the free words
    and expanded edge paths is essential for the canonical-dissection formula
    for Riemann constants; a symplectic homology matrix is not sufficient.
    """
    if cut_system is None:
        cut_system = _ribbon_tree_cotree_cut_system(graph)
    generator_index = {
        edge: index for index, edge in enumerate(
            cut_system.generator_edges)
    }
    boundary_word = tuple(
        (generator_index[edge], orientation)
        for edge, orientation in cut_system.boundary_word)
    pairs = _brahana_canonical_words(boundary_word)
    a_words = tuple(pair[0] for pair in pairs)
    b_words = tuple(pair[1] for pair in pairs)
    a_loops = tuple(_expand_cut_system_word(
        word, cut_system.loops) for word in a_words)
    b_loops = tuple(_expand_cut_system_word(
        word, cut_system.loops) for word in b_words)

    loops = a_loops + b_loops
    cycles = []
    for loop in loops:
        coefficients = [0] * len(graph.edges)
        for edge, orientation in loop:
            coefficients[edge] += orientation
        cycles.append(tuple(coefficients))
    intersection = tuple(
        tuple(_ribbon_cycle_intersection(
            graph.edges, graph.rotation, left, right)
            for right in cycles)
        for left in cycles)
    genus = graph.genus
    expected = tuple(tuple(
        1 if row < genus and column == genus + row
        else -1 if column < genus and row == genus + column
        else 0
        for column in range(2 * genus))
        for row in range(2 * genus))
    if intersection != expected:
        raise ValueError(
            "canonical polygon loops have the wrong intersection form")
    return _CanonicalPolygon(
        root=cut_system.root,
        a_words=a_words,
        b_words=b_words,
        a_loops=a_loops,
        b_loops=b_loops,
        relator=boundary_word,
        intersection=intersection,
    )


def _ribbon_cycle_intersection(edges, rotation, left, right):
    """Return the oriented intersection of two graph cycles."""
    numerator = 0
    for vertex, half_edges in rotation.items():
        left_flows = []
        right_flows = []
        for edge_index, endpoint in half_edges:
            orientation = 1 if endpoint == 0 else -1
            left_flows.append(orientation * left[edge_index])
            right_flows.append(orientation * right[edge_index])
        for first in range(len(half_edges)):
            for second in range(first + 1, len(half_edges)):
                numerator += (
                    left_flows[first] * right_flows[second]
                    - right_flows[first] * left_flows[second])
    if numerator % 2:
        raise ValueError("ribbon intersection is not integral")
    # The half-edge rotations above follow positive base-plane monodromy.
    # Their local outward-flow ordering is opposite the complex orientation
    # convention in which a canonical pair satisfies a . b = +1.
    return -numerator // 2


def _lifted_monodromy_graph(permutations, branch_orientations=None):
    """Construct the lifted ribbon graph of a Hurwitz monodromy system."""
    permutations = tuple(tuple(permutation)
                         for permutation in permutations)
    if not permutations:
        raise ValueError("at least one monodromy permutation is required")
    degree = len(permutations[0])
    if not degree or any(len(permutation) != degree
                         for permutation in permutations):
        raise ValueError("monodromy permutations must have one common degree")
    for permutation in permutations:
        _permutation_cycles(permutation, include_fixed=True)
    if branch_orientations is None:
        branch_orientations = (1,) * len(permutations)
    else:
        branch_orientations = tuple(branch_orientations)
    if (len(branch_orientations) != len(permutations)
            or any(value not in (-1, 1)
                   for value in branch_orientations)):
        raise ValueError("branch orientations must be +1 or -1")
    if len(_monodromy_orbit(permutations)) != degree:
        raise ValueError("the monodromy action is not transitive")

    branch_cycles = tuple(
        _permutation_cycles(permutation, include_fixed=True)
        for permutation in permutations)
    base_vertices = tuple(("base", sheet) for sheet in range(degree))
    branch_vertices = tuple(
        ("branch", branch_index, cycle_index)
        for branch_index, cycles in enumerate(branch_cycles)
        for cycle_index in range(len(cycles)))
    vertices = base_vertices + branch_vertices

    edges = []
    edge_lookup = {}
    rotation = {vertex: [] for vertex in vertices}
    for branch_index, cycles in enumerate(branch_cycles):
        for cycle_index, cycle in enumerate(cycles):
            branch_vertex = ("branch", branch_index, cycle_index)
            # A positively oriented generator induces the inverse cyclic
            # order on the lifted radial half-edges.  A negative orientation
            # reverses both this rotation and the later numerical word
            # realization.  Notice that the clockwise outer circle used for
            # infinity is positive here: in the local coordinate z=1/x it is
            # counter-clockwise around z=0.
            ordered_cycle = (tuple(reversed(cycle))
                             if branch_orientations[branch_index] == 1
                             else cycle)
            for sheet in ordered_cycle:
                edge_index = len(edges)
                base_vertex = ("base", sheet)
                edges.append(_LiftedGraphEdge(
                    base_vertex, branch_vertex, branch_index, sheet))
                edge_lookup[branch_index, sheet] = edge_index
                rotation[branch_vertex].append((edge_index, 1))
    for sheet in range(degree):
        rotation[("base", sheet)] = [
            (edge_lookup[branch_index, sheet], 0)
            for branch_index in range(len(permutations))]

    parent = {vertex: vertex for vertex in vertices}

    def find(vertex):
        while parent[vertex] != vertex:
            parent[vertex] = parent[parent[vertex]]
            vertex = parent[vertex]
        return vertex

    tree_edges = []
    chord_edges = []
    for edge_index, edge in enumerate(edges):
        left_root = find(edge.tail)
        right_root = find(edge.head)
        if left_root == right_root:
            chord_edges.append(edge_index)
        else:
            parent[left_root] = right_root
            tree_edges.append(edge_index)
    if len(tree_edges) != len(vertices) - 1:
        raise ValueError("lifted monodromy graph is disconnected")

    adjacency = {vertex: [] for vertex in vertices}
    for edge_index in tree_edges:
        edge = edges[edge_index]
        adjacency[edge.tail].append((edge.head, edge_index, 1))
        adjacency[edge.head].append((edge.tail, edge_index, -1))
    cycles = []
    for chord in chord_edges:
        edge = edges[chord]
        coefficients = [0] * len(edges)
        coefficients[chord] = 1
        for tree_edge, orientation in _tree_path(
                adjacency, edge.head, edge.tail):
            coefficients[tree_edge] += orientation
        cycles.append(tuple(coefficients))

    intersection = tuple(
        tuple(_ribbon_cycle_intersection(
            edges, rotation, left, right) for right in cycles)
        for left in cycles)
    genus, unused_ramification = _riemann_hurwitz_genus(
        degree, permutations)
    boundary_components = _ribbon_boundary_count(edges, rotation)
    intersection_rank = _integer_matrix_rank(intersection)
    expected_cycle_rank = 2 * genus + degree - 1
    if len(cycles) != expected_cycle_rank:
        raise ValueError("lifted graph has an inconsistent cycle rank")
    if boundary_components != degree:
        raise ValueError("lifted graph has an inconsistent ribbon boundary")
    if intersection_rank != 2 * genus:
        raise ValueError("lifted graph has an inconsistent intersection rank")
    return _LiftedMonodromyGraph(
        degree=degree,
        genus=genus,
        permutations=permutations,
        branch_orientations=branch_orientations,
        branch_cycles=branch_cycles,
        vertices=vertices,
        edges=tuple(edges),
        rotation={vertex: tuple(half_edges)
                  for vertex, half_edges in rotation.items()},
        tree_edges=tuple(tree_edges),
        chord_edges=tuple(chord_edges),
        cycles=tuple(cycles),
        intersection=intersection,
        boundary_components=boundary_components,
        intersection_rank=intersection_rank,
    )


def _graph_cycle_word(graph, cycle):
    """Convert one simple ribbon-graph cycle to branch-loop instructions."""
    if len(cycle) != len(graph.edges):
        raise ValueError("graph cycle has the wrong edge dimension")
    outgoing = {}
    incoming = {}
    for edge_index, coefficient in enumerate(cycle):
        if coefficient not in (-1, 0, 1):
            raise ValueError("graph cycle must be a simple oriented cycle")
        if not coefficient:
            continue
        edge = graph.edges[edge_index]
        if coefficient == 1:
            start, end = edge.tail, edge.head
        else:
            start, end = edge.head, edge.tail
        if start in outgoing or end in incoming:
            raise ValueError("graph cycle is not a single simple cycle")
        outgoing[start] = end
        incoming[end] = start
    if set(outgoing) != set(incoming):
        raise ValueError("graph cycle has nonzero boundary")

    base_vertices = sorted(
        vertex for vertex in outgoing if vertex[0] == "base")
    if not base_vertices:
        raise ValueError("graph cycle contains no base-sheet vertex")
    start_vertex = base_vertices[0]
    current = start_vertex
    steps = []
    visited = set()
    while current not in visited:
        visited.add(current)
        branch_vertex = outgoing.get(current)
        if (current[0] != "base" or branch_vertex is None
                or branch_vertex[0] != "branch"):
            raise ValueError("graph cycle does not alternate vertex types")
        if branch_vertex in visited:
            raise ValueError("graph cycle repeats a branch vertex")
        visited.add(branch_vertex)
        next_base = outgoing.get(branch_vertex)
        if next_base is None or next_base[0] != "base":
            raise ValueError("graph cycle does not alternate vertex types")
        branch_index = branch_vertex[1]
        permutation = graph.permutations[branch_index]
        sheet = current[1]
        target = next_base[1]
        image = sheet
        turns = 0
        while turns < graph.degree and image != target:
            image = permutation[image]
            turns += 1
        if not turns or image != target:
            raise ValueError("branch transition disagrees with monodromy")
        steps.append(_BranchLoopStep(branch_index, turns))
        current = next_base
    if current != start_vertex or visited != set(outgoing):
        raise ValueError("graph cycle is disconnected")
    return _GraphCycleWord(start_vertex[1], tuple(steps))


def _monodromy_branch_continuations(ctx, monodromy):
    """Return finite branch loops followed by a numerical infinity loop."""
    finite = tuple(monodromy.continuations)
    if not finite:
        raise ValueError("finite monodromy continuations are required")
    finite_product = finite[0]
    for continuation in finite[1:]:
        finite_product = _concatenate_plane_curve_continuations(
            ctx, finite_product, continuation)
    infinity = _reverse_plane_curve_continuation(ctx, finite_product)
    infinity = _align_closed_continuation_base_fibre(
        ctx, infinity, finite[0].fibres[0])
    if infinity.permutation != monodromy.infinity_permutation:
        raise ValueError("numerical infinity monodromy is inconsistent")
    return finite + (infinity,)


def _monodromy_graph_permutations(monodromy):
    """Return the permutations for branched fibres in numerical order.

    Finite entries retain their continuation indices.  Infinity is appended
    only when it is ramified: an identity permutation represents several
    ordinary points over infinity, not a branch fibre of the covering.
    """
    permutations = monodromy.permutations
    identity = tuple(range(len(monodromy.base_sheets)))
    if monodromy.infinity_permutation != identity:
        permutations += (monodromy.infinity_permutation,)
    return permutations


def _continue_graph_cycle_word(
        ctx, branch_continuations, word, branch_orientations=None):
    """Return the numerical continuation represented by a branch-loop word."""
    if branch_orientations is None:
        branch_orientations = (1,) * len(branch_continuations)
    if len(branch_orientations) != len(branch_continuations):
        raise ValueError("branch orientations and continuations differ")
    result = None
    sheet = word.start_sheet
    for step in word.steps:
        try:
            continuation = branch_continuations[step.branch_index]
            orientation = branch_orientations[step.branch_index]
        except IndexError:
            raise ValueError("branch-loop word has an invalid branch index")
        repeats = step.turns
        if orientation == -1:
            permutation = continuation.permutation
            cycle_length = 1
            image = permutation[sheet]
            while image != sheet:
                image = permutation[image]
                cycle_length += 1
                if cycle_length > len(permutation):
                    raise ValueError("invalid branch permutation cycle")
            repeats = cycle_length - step.turns
            continuation = _reverse_plane_curve_continuation(
                ctx, continuation)
            continuation = _align_closed_continuation_base_fibre(
                ctx, continuation,
                branch_continuations[step.branch_index].fibres[0])
        elif orientation != 1:
            raise ValueError("branch orientations must be +1 or -1")
        for unused in range(repeats):
            if result is None:
                result = continuation
            else:
                result = _concatenate_plane_curve_continuations(
                    ctx, result, continuation)
        for unused in range(step.turns):
            sheet = branch_continuations[
                step.branch_index].permutation[sheet]
    if result is None:
        raise ValueError("branch-loop word must not be empty")
    return result


def _numerical_graph_cycles_from_continuations(
        ctx, graph, branch_continuations):
    """Lift graph cycles using continuations in the graph's ribbon order."""
    branch_continuations = tuple(branch_continuations)
    if tuple(continuation.permutation
             for continuation in branch_continuations) != graph.permutations:
        raise ValueError("graph and numerical monodromy systems differ")
    words = tuple(_graph_cycle_word(graph, cycle)
                  for cycle in graph.cycles)
    chains = []
    for word in words:
        continuation = _continue_graph_cycle_word(
            ctx, branch_continuations, word, graph.branch_orientations)
        chain = _prepare_lifted_path_chain((
            (1, continuation, word.start_sheet),))
        if _lifted_path_chain_boundary(ctx, chain):
            raise ValueError("numerical graph cycle has nonzero boundary")
        chains.append(chain)
    return _NumericalGraphCycles(
        branch_continuations=branch_continuations,
        words=words,
        chains=tuple(chains),
    )


def _numerical_graph_cycles(ctx, graph, monodromy):
    """Lift cycles from a finite-then-infinity monodromy system."""
    expected = _monodromy_graph_permutations(monodromy)
    if graph.permutations != expected:
        raise ValueError("graph and numerical monodromy systems differ")
    branch_continuations = _monodromy_branch_continuations(ctx, monodromy)
    if len(branch_continuations) != len(expected):
        # The only omitted continuation is an unramified identity at infinity.
        branch_continuations = branch_continuations[:-1]
    return _numerical_graph_cycles_from_continuations(
        ctx, graph, branch_continuations)


def _ordered_monodromy_graph(monodromy):
    """Construct a graph from explicitly ribbon-ordered generators."""
    identity = tuple(range(len(monodromy.base_sheets)))
    generators = tuple(
        generator for generator in monodromy.ribbon_generators
        if generator.permutation != identity)
    permutations = tuple(
        generator.permutation for generator in generators)
    # Finite loops are counter-clockwise in x.  The clockwise outer circle is
    # likewise positive at infinity because z=1/x reverses its apparent
    # affine orientation.
    orientations = (1,) * len(generators)
    return _lifted_monodromy_graph(permutations, orientations)


def _numerical_ordered_graph_cycles(ctx, graph, monodromy):
    """Lift graph cycles using explicitly ribbon-ordered continuations."""
    identity = tuple(range(len(monodromy.base_sheets)))
    generators = tuple(
        generator for generator in monodromy.ribbon_generators
        if generator.permutation != identity)
    expected = tuple(generator.permutation for generator in generators)
    if graph.permutations != expected:
        raise ValueError("graph and ordered monodromy systems differ")
    continuations = tuple(
        generator.continuation for generator in generators)
    return _numerical_graph_cycles_from_continuations(
        ctx, graph, continuations)


def _graph_loop_coefficients(graph, loop):
    """Return an edge-chain vector for an oriented graph-edge loop."""
    coefficients = [0] * len(graph.edges)
    for edge, orientation in loop:
        coefficients[edge] += orientation
    return tuple(coefficients)


def _graph_path_branch_word(graph, path, start_vertex):
    """Convert an oriented base-to-base graph path to branch-loop steps."""
    current = start_vertex
    vertices = [current]
    for edge_index, orientation in path:
        edge = graph.edges[edge_index]
        source, target = ((edge.tail, edge.head) if orientation == 1
                          else (edge.head, edge.tail))
        if source != current:
            raise ValueError("oriented graph path is not continuous")
        current = target
        vertices.append(current)
    if (vertices[0][0] != "base" or vertices[-1][0] != "base"
            or len(path) % 2):
        raise ValueError("graph connector must run between base vertices")

    steps = []
    for index in range(0, len(path), 2):
        left = vertices[index]
        branch = vertices[index + 1]
        right = vertices[index + 2]
        if (left[0] != "base" or branch[0] != "branch"
                or right[0] != "base"):
            raise ValueError("graph connector does not alternate vertices")
        branch_index = branch[1]
        permutation = graph.permutations[branch_index]
        image = left[1]
        turns = 0
        while image != right[1] and turns < graph.degree:
            image = permutation[image]
            turns += 1
        if image != right[1]:
            raise ValueError("graph connector disagrees with monodromy")
        if turns:
            steps.append(_BranchLoopStep(branch_index, turns))
    return _GraphCycleWord(vertices[0][1], tuple(steps))


def _concatenate_generator_continuations(ctx, word, continuations):
    """Realize a free word in closed, commonly based continuations."""
    result = None
    for generator, orientation in word:
        try:
            continuation = continuations[generator]
        except IndexError:
            raise ValueError("canonical word has an invalid generator")
        if orientation == -1:
            continuation = _reverse_plane_curve_continuation(
                ctx, continuation)
        elif orientation != 1:
            raise ValueError("word orientations must be +1 or -1")
        result = (continuation if result is None else
                  _concatenate_plane_curve_continuations(
                      ctx, result, continuation))
    if result is None:
        raise ValueError("canonical generator word must not be empty")
    return result


def _based_cut_generator_continuations(
        ctx, graph, cut_system, branch_continuations):
    """Realize cut generators as connector-cycle-connector inverse loops."""
    adjacency = {vertex: [] for vertex in graph.vertices}
    for edge_index in cut_system.tree_edges:
        edge = graph.edges[edge_index]
        adjacency[edge.tail].append((edge.head, edge_index, 1))
        adjacency[edge.head].append((edge.tail, edge_index, -1))
    result = []
    for loop in cut_system.loops:
        simple_word = _graph_cycle_word(
            graph, _graph_loop_coefficients(graph, loop))
        simple = _continue_graph_cycle_word(
            ctx, branch_continuations, simple_word,
            graph.branch_orientations)
        cycle_base = ("base", simple_word.start_sheet)
        connector_path = _tree_path(
            adjacency, cut_system.root, cycle_base)
        connector_word = _graph_path_branch_word(
            graph, connector_path, cut_system.root)
        if connector_word.steps:
            connector = _continue_graph_cycle_word(
                ctx, branch_continuations, connector_word,
                graph.branch_orientations)
            based = _concatenate_plane_curve_continuations(
                ctx, connector, simple)
            based = _concatenate_plane_curve_continuations(
                ctx, based,
                _reverse_plane_curve_continuation(ctx, connector))
        else:
            based = simple
        if based.permutation[cut_system.root[1]] != cut_system.root[1]:
            raise ValueError("based cut generator does not close")
        result.append(based)
    return tuple(result)


def _oriented_word_exponents(word, size):
    """Return the abelianized coefficient row of an oriented word."""
    result = [0] * size
    for symbol, orientation in word:
        if (not isinstance(symbol, int) or symbol < 0 or symbol >= size
                or orientation not in (-1, 1)):
            raise ValueError("word has an invalid generator")
        result[symbol] += orientation
    return tuple(result)


def _numerical_canonical_polygon_from_continuations(
        ctx, graph, branch_continuations, cut_system=None):
    """Lift the homology chains induced by a canonical ribbon polygon.

    The polygon retains full based free words separately.  Ordinary period
    integration depends only on their abelianized chains; iterated integrals
    must later realize the based words without dropping tree conjugations.
    """
    branch_continuations = tuple(branch_continuations)
    if tuple(continuation.permutation
             for continuation in branch_continuations) != graph.permutations:
        raise ValueError("graph and numerical monodromy systems differ")
    if cut_system is None:
        cut_system = _ribbon_tree_cotree_cut_system(graph)
    polygon = _canonical_ribbon_polygon(graph, cut_system)
    numerical = _numerical_graph_cycles_from_continuations(
        ctx, graph, branch_continuations)
    generator_transformation = tuple(tuple(
        _graph_loop_coefficients(graph, loop)[chord]
        for chord in graph.chord_edges)
        for loop in cut_system.loops)
    generator_chains = _transform_lifted_path_chains(
        numerical.chains, generator_transformation)
    words = polygon.a_words + polygon.b_words
    canonical_transformation = tuple(
        _oriented_word_exponents(word, len(generator_chains))
        for word in words)
    compact_transformation = tuple(tuple(sum(
        canonical_transformation[row][middle]
        * generator_transformation[middle][column]
        for middle in range(len(generator_transformation)))
        for column in range(len(graph.cycles)))
        for row in range(2 * graph.genus))
    reduction = _symplectic_reduce_intersection(graph.intersection)
    transformation = (compact_transformation
                      + reduction.transformation[2 * graph.genus:])
    if abs(_integer_determinant(transformation)) != 1:
        raise ValueError("canonical polygon transformation is not primitive")
    intersection_form = tuple(tuple(sum(
        transformation[row][left] * graph.intersection[left][right]
        * transformation[column][right]
        for left in range(len(graph.cycles))
        for right in range(len(graph.cycles)))
        for column in range(len(graph.cycles)))
        for row in range(len(graph.cycles)))
    if intersection_form != reduction.form:
        raise ValueError(
            "canonical polygon transformation has the wrong intersection")
    chains = _transform_lifted_path_chains(
        numerical.chains, compact_transformation)
    if any(_lifted_path_chain_boundary(ctx, chain) for chain in chains):
        raise ValueError("canonical polygon chain has nonzero boundary")
    genus = graph.genus
    generator_continuations = _based_cut_generator_continuations(
        ctx, graph, cut_system, branch_continuations)
    a_continuations = tuple(
        _concatenate_generator_continuations(
            ctx, word, generator_continuations)
        for word in polygon.a_words)
    b_continuations = tuple(
        _concatenate_generator_continuations(
            ctx, word, generator_continuations)
        for word in polygon.b_words)
    if any(continuation.permutation[cut_system.root[1]]
           != cut_system.root[1]
           for continuation in a_continuations + b_continuations):
        raise ValueError("canonical based generator does not close")
    return _NumericalCanonicalPolygon(
        polygon=polygon,
        generator_chains=generator_chains,
        a_chains=chains[:genus],
        b_chains=chains[genus:],
        chains=chains,
        generator_continuations=generator_continuations,
        a_continuations=a_continuations,
        b_continuations=b_continuations,
        transformation=transformation,
        intersection_form=intersection_form,
    )


def _numerical_ordered_canonical_polygon(
        ctx, graph, monodromy, cut_system=None):
    """Lift canonical loops using ribbon-ordered numerical generators."""
    identity = tuple(range(len(monodromy.base_sheets)))
    generators = tuple(
        generator for generator in monodromy.ribbon_generators
        if generator.permutation != identity)
    expected = tuple(generator.permutation for generator in generators)
    if graph.permutations != expected:
        raise ValueError("graph and ordered monodromy systems differ")
    return _numerical_canonical_polygon_from_continuations(
        ctx, graph,
        tuple(generator.continuation for generator in generators),
        cut_system=cut_system)


def _numerical_canonical_polygon(
        ctx, graph, monodromy, cut_system=None):
    """Lift canonical loops from a finite-then-infinity monodromy system."""
    expected = _monodromy_graph_permutations(monodromy)
    if graph.permutations != expected:
        raise ValueError("graph and numerical monodromy systems differ")
    continuations = _monodromy_branch_continuations(ctx, monodromy)
    if len(continuations) != len(expected):
        continuations = continuations[:-1]
    return _numerical_canonical_polygon_from_continuations(
        ctx, graph, continuations, cut_system=cut_system)


def _transform_lifted_path_chains(chains, transformation):
    """Apply an integer row transformation to lifted-path chains."""
    chains = tuple(chains)
    transformed = []
    for row in transformation:
        if len(row) != len(chains):
            raise ValueError("chain transformation has the wrong width")
        terms = []
        for coefficient, chain in zip(row, chains):
            if not isinstance(coefficient, int):
                raise ValueError("chain transformation must be integral")
            terms.extend(
                (coefficient * term.coefficient,
                 term.continuation, term.sheet)
                for term in chain.terms)
        transformed.append(_prepare_lifted_path_chain(terms))
    return tuple(transformed)


def _shortest_monodromy_word(permutations, start, target):
    """Return generator indices carrying one sheet label to another."""
    pending = [(start, ())]
    visited = {start}
    while pending:
        sheet, word = pending.pop(0)
        if sheet == target:
            return word
        for index, permutation in enumerate(permutations):
            image = permutation[sheet]
            if image not in visited:
                visited.add(image)
                pending.append((image, word + (index,)))
    raise ValueError("monodromy does not connect the requested sheets")


def _concatenate_continuation_sequence(ctx, continuations):
    result = None
    for continuation in continuations:
        result = (continuation if result is None else
                  _concatenate_plane_curve_continuations(
                      ctx, result, continuation))
    return result


def _chain_as_common_base_loop(ctx, chain, monodromy):
    """Realize an integral cycle chain as one loop based on sheet zero."""
    generators = tuple(monodromy.ribbon_generators)
    permutations = tuple(
        generator.permutation for generator in generators)
    loops = []
    for term in chain.terms:
        word = _shortest_monodromy_word(
            permutations, 0, term.sheet)
        connector = _concatenate_continuation_sequence(
            ctx, tuple(generators[index].continuation for index in word))
        pieces = []
        if connector is not None:
            pieces.append(connector)
        pieces.append(term.continuation)
        if connector is not None:
            pieces.append(_reverse_plane_curve_continuation(ctx, connector))
        loop = _concatenate_continuation_sequence(ctx, pieces)
        if term.coefficient < 0:
            loop = _reverse_plane_curve_continuation(ctx, loop)
        loops.extend((loop,) * abs(term.coefficient))
    if not loops:
        raise ValueError("canonical cycle must not be empty")
    result = _concatenate_continuation_sequence(ctx, loops)
    start, end = _lifted_path_endpoints(_LiftedPathTerm(1, result, 0))
    if not _same_numerical_place(ctx, start, end):
        raise ValueError("canonical cycle did not close at the common base")
    return result


def _radial_plane_curve_monodromy(
        ctx, curve, branch_points, base_point=None, circle_steps=24,
        max_refinements=12):
    """Compute an ordered monodromy system for complex branch values.

    Finite positive loops use guarded radial spokes from an exterior base
    point.  Their counter-clockwise product order and clockwise outward
    ribbon order are retained separately.  A clockwise outer circle supplies
    the positive generator at infinity geometrically.
    """
    points = tuple(ctx.convert(point) for point in branch_points)
    base_point, center, radii, minimum_clearance = (
        _radial_branch_geometry(ctx, points, base_point=base_point))
    base_sheets = _ordered_plane_curve_sheets(ctx, curve, base_point)
    geometry = tuple(zip(points, radii))
    product_geometry = tuple(sorted(
        geometry, key=lambda item: ctx.arg(item[0] - base_point)))
    finite_generators = []
    for point, radius in product_geometry:
        path = _radial_branch_loop_path(
            ctx, base_point, point, radius, circle_steps=circle_steps)
        continuation = _continue_plane_curve_sheets_adaptive(
            ctx, curve, path, initial_sheets=base_sheets,
            max_refinements=max_refinements)
        if continuation.permutation is None:
            raise ValueError("radial monodromy paths must be closed")
        if continuation.permutation == tuple(range(curve.y_degree)):
            raise ValueError("finite branch loop has identity monodromy")
        finite_generators.append(_BranchGenerator(
            kind="finite",
            value=point,
            permutation=continuation.permutation,
            continuation=continuation,
            radius=radius,
        ))

    outer_steps = 4 * circle_steps
    outer_vector = base_point - center
    infinity_path = tuple(
        center + outer_vector * ctx.exp(
            -2 * ctx.j * ctx.pi * step / outer_steps)
        for step in range(outer_steps + 1))
    infinity_continuation = _continue_plane_curve_sheets_adaptive(
        ctx, curve, infinity_path, initial_sheets=base_sheets,
        max_refinements=max_refinements)
    if infinity_continuation.permutation is None:
        raise ValueError("infinity monodromy path must be closed")
    infinity = _BranchGenerator(
        kind="infinity",
        value=ctx.inf,
        permutation=infinity_continuation.permutation,
        continuation=infinity_continuation,
        radius=abs(outer_vector),
    )
    product_generators = tuple(finite_generators) + (infinity,)
    product = tuple(range(curve.y_degree))
    for generator in product_generators:
        product = _compose_permutations(generator.permutation, product)
    if product != tuple(range(curve.y_degree)):
        raise ValueError("radial monodromy product is not the identity")

    # The cyclic order at the common base point is geometric, not in
    # general the reverse of the continuation-product order.  In particular,
    # the outgoing tangent of the outer infinity circle can lie between two
    # finite spokes.  Sorting all generators by that tangent gives the ribbon
    # rotation used by the lifted graph (up to an irrelevant cyclic shift).
    # Using a guessed order can leave a nominal radical cycle with a nonzero
    # holomorphic period.
    def outgoing_angle(generator):
        path = generator.continuation.path
        for left, right in zip(path, path[1:]):
            if right != left:
                return ctx.arg(right - left)
        raise ValueError("monodromy generator has no outgoing tangent")

    # ``rotation`` is stored clockwise by the ribbon-graph conventions used
    # below, hence the descending angular order.
    ribbon_generators = tuple(sorted(
        product_generators, key=outgoing_angle, reverse=True))
    permutations = tuple(
        generator.permutation for generator in ribbon_generators)
    if len(_monodromy_orbit(permutations)) != curve.y_degree:
        raise ValueError("the monodromy action is not transitive")
    genus, ramification = _riemann_hurwitz_genus(
        curve.y_degree, permutations)
    return _OrderedMonodromyData(
        base_point=base_point,
        base_sheets=base_sheets,
        center=center,
        branch_points=tuple(
            generator.value for generator in finite_generators),
        product_generators=product_generators,
        ribbon_generators=ribbon_generators,
        ramification=ramification,
        genus=genus,
        minimum_clearance=minimum_clearance,
    )



def _real_plane_curve_monodromy(
        ctx, curve, base_point, branch_points, circle_steps=24,
        corridor_height=None, max_refinements=12):
    """Compute monodromy for distinct real finite branch values.

    Infinity is inferred as the inverse of the ordered finite product.  The
    returned continuations retain the numerical evidence for every branch
    permutation.
    """
    branch_points = tuple(sorted(ctx.convert(point)
                                 for point in branch_points))
    if not branch_points:
        raise ValueError("at least one finite branch point is required")
    base_point = ctx.convert(base_point)
    base_sheets = _ordered_plane_curve_sheets(ctx, curve, base_point)
    continuations = []
    for branch_point in branch_points:
        path = _real_branch_loop_path(
            ctx, base_point, branch_point, branch_points,
            circle_steps=circle_steps, corridor_height=corridor_height)
        continuations.append(_continue_plane_curve_sheets_adaptive(
            ctx, curve, path, initial_sheets=base_sheets,
            max_refinements=max_refinements))
    permutations = tuple(result.permutation for result in continuations)
    if any(permutation is None for permutation in permutations):
        raise ValueError("monodromy paths must be closed")

    finite_product = tuple(range(curve.y_degree))
    for permutation in permutations:
        finite_product = _compose_permutations(
            permutation, finite_product)
    infinity_permutation = _inverse_permutation(finite_product)
    all_permutations = permutations + (infinity_permutation,)
    if len(_monodromy_orbit(all_permutations)) != curve.y_degree:
        raise ValueError("the monodromy action is not transitive")
    genus, ramification = _riemann_hurwitz_genus(
        curve.y_degree, all_permutations)
    return _MonodromyData(
        base_point=base_point,
        base_sheets=base_sheets,
        branch_points=branch_points,
        permutations=permutations,
        infinity_permutation=infinity_permutation,
        ramification=ramification,
        genus=genus,
        continuations=tuple(continuations),
    )
