"""Radial-loop monodromy diagnostics and sheet permutation utilities."""

from ._records import _BranchGenerator, _OrderedMonodromyData
from .continuation import (
    _continue_plane_curve_sheets_adaptive,
    _radial_branch_geometry,
    _radial_branch_loop_path,
)
from .polynomial import _ordered_plane_curve_sheets


def _compose_permutations(left, right):
    """Return ``left`` after ``right`` for permutation image tuples."""
    if len(left) != len(right):
        raise ValueError("permutations must have equal sizes")
    return tuple(left[right[index]] for index in range(len(left)))


def _permutation_cycles(permutation, include_fixed=False):
    """Return the disjoint cycles of a permutation."""
    if sorted(permutation) != list(range(len(permutation))):
        raise ValueError("invalid permutation")
    visited = set()
    cycles = []
    for start in range(len(permutation)):
        if start in visited:
            continue
        cycle = []
        current = start
        while current not in visited:
            visited.add(current)
            cycle.append(current)
            current = permutation[current]
        if include_fixed or len(cycle) > 1:
            cycles.append(tuple(cycle))
    return tuple(cycles)


def _monodromy_orbit(permutations, start=0):
    """Return the sheet orbit generated by a sequence of permutations."""
    orbit = {start}
    pending = [start]
    while pending:
        sheet = pending.pop()
        for permutation in permutations:
            image = permutation[sheet]
            if image not in orbit:
                orbit.add(image)
                pending.append(image)
    return frozenset(orbit)


def _riemann_hurwitz_genus(degree, permutations):
    """Return genus and total ramification for a connected sphere cover."""
    ramification = sum(
        sum(len(cycle) - 1
            for cycle in _permutation_cycles(permutation))
        for permutation in permutations)
    numerator = 2 - 2 * degree + ramification
    if numerator < 0 or numerator % 2:
        raise ValueError("monodromy data do not define a valid genus")
    return numerator // 2, ramification


def _radial_plane_curve_monodromy(
        ctx, curve, branch_points, base_point=None, circle_steps=24,
        max_refinements=12):
    """Compute an ordered monodromy system for complex branch values.

    Finite positive loops use guarded radial spokes from an exterior base
    point.  Their counter-clockwise product order and clockwise outward
    ribbon order are retained separately.  A clockwise outer circle supplies
    the positive generator at infinity geometrically.
    """
    points = tuple(ctx.convert(point) for point in branch_points)
    base_point, center, radii, minimum_clearance = (
        _radial_branch_geometry(ctx, points, base_point=base_point))
    base_sheets = _ordered_plane_curve_sheets(ctx, curve, base_point)
    geometry = tuple(zip(points, radii))
    # All branch values lie inside the radial center's spread circle. Measure
    # angles from the inward ray so the principal-argument cut cannot split
    # one cyclic block of finite spokes across -pi and pi.
    inward = center - base_point
    product_geometry = tuple(sorted(
        geometry, key=lambda item: ctx.arg(
            (item[0] - base_point) / inward)))
    finite_generators = []
    for point, radius in product_geometry:
        path = _radial_branch_loop_path(
            ctx, base_point, point, radius, circle_steps=circle_steps)
        continuation = _continue_plane_curve_sheets_adaptive(
            ctx, curve, path, initial_sheets=base_sheets,
            max_refinements=max_refinements)
        if continuation.permutation is None:
            raise ValueError("radial monodromy paths must be closed")
        if continuation.permutation == tuple(range(curve.y_degree)):
            raise ValueError("finite branch loop has identity monodromy")
        finite_generators.append(_BranchGenerator(
            kind="finite",
            value=point,
            permutation=continuation.permutation,
            continuation=continuation,
            radius=radius,
        ))

    # The exterior circle has greater clearance than the finite loops.
    # Adaptive continuation inserts additional points if a chord is unsafe.
    outer_steps = circle_steps
    outer_vector = base_point - center
    infinity_path = tuple(
        center + outer_vector * ctx.exp(
            -2 * ctx.j * ctx.pi * step / outer_steps)
        for step in range(outer_steps + 1))
    infinity_continuation = _continue_plane_curve_sheets_adaptive(
        ctx, curve, infinity_path, initial_sheets=base_sheets,
        max_refinements=max_refinements)
    if infinity_continuation.permutation is None:
        raise ValueError("infinity monodromy path must be closed")
    infinity = _BranchGenerator(
        kind="infinity",
        value=ctx.inf,
        permutation=infinity_continuation.permutation,
        continuation=infinity_continuation,
        radius=abs(outer_vector),
    )
    product_generators = tuple(finite_generators) + (infinity,)
    product = tuple(range(curve.y_degree))
    for generator in product_generators:
        product = _compose_permutations(generator.permutation, product)
    if product != tuple(range(curve.y_degree)):
        raise ValueError("radial monodromy product is not the identity")

    # The cyclic order at the common base point is geometric, not in
    # general the reverse of the continuation-product order.  In particular,
    # the outgoing tangent of the outer infinity circle can lie between two
    # finite spokes.  Sorting all generators by that tangent gives the ribbon
    # rotation used by the lifted graph (up to an irrelevant cyclic shift).
    # Using a guessed order can leave a nominal radical cycle with a nonzero
    # holomorphic period.
    def outgoing_angle(generator):
        path = generator.continuation.path
        for left, right in zip(path, path[1:]):
            if right != left:
                return ctx.arg(right - left)
        raise ValueError("monodromy generator has no outgoing tangent")

    # ``rotation`` is stored clockwise by the ribbon-graph conventions used
    # below, hence the descending angular order.
    ribbon_generators = tuple(sorted(
        product_generators, key=outgoing_angle, reverse=True))
    permutations = tuple(
        generator.permutation for generator in ribbon_generators)
    if len(_monodromy_orbit(permutations)) != curve.y_degree:
        raise ValueError("the monodromy action is not transitive")
    genus, ramification = _riemann_hurwitz_genus(
        curve.y_degree, permutations)
    return _OrderedMonodromyData(
        base_point=base_point,
        base_sheets=base_sheets,
        center=center,
        branch_points=tuple(
            generator.value for generator in finite_generators),
        product_generators=product_generators,
        ribbon_generators=ribbon_generators,
        ramification=ramification,
        genus=genus,
        minimum_clearance=minimum_clearance,
    )
